### ISSUE TITLE
Linking CXX shared library ./../lib/libRDGeneral.dylib

### ISSUE THREAD

**Issue by supern8ent** [rdkit/homebrew-rdkit#20]
I encountered an error while installing rdkit via brew on osx 10.9.5. Here's what happened:

    $ brew tap rdkit/rdkit
    $ brew install rdkit

...some dependencies are installed, then

    ==> Installing rdki

...

    ==> make
    make[1]: *** [Code/RDBoost/CMakeFiles/RDBoost.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    Linking CXX shared library ../../lib/libRDGeneral.dylib
    [  5%] Built target RDGeneral
    make: *** [all] Error 2

brew gist-logs rdkit:
https://gist.github.com/a437c40ea71027f3d1a6

In case it matters, I use virtualenvwrapper and had one activated when I ran brew install rdkit

**Comment by mcs07** [comment]
I think the virtualenv is the cause of this problem. As it stands, RDKit doesn't have very good support for virtualenvs. You can see in the cmake log:

    -- Found PythonInterp: /Users/nathan/.virtualenvs/A0/bin/python (found version "2.7.6") 
    -- Found PythonLibs: /Users/nathan/.virtualenvs/A0/lib/libpython2.7.dylib (found version "2.7.6") 

I don't think that `libpython2.7.dylib` actually exists within each virtualenv? They use the lib in the main python installation.

Ideally RDKit could support virtualenvs by having a separate python package that could be installed with `pip` that just installed the python language bindings into a virtualenv's `site-packages` directory, with all virtualenvs just referring to a main RDKit installation. Open Babel manages this with its swig-based language bindings, but unfortunately I'm not sure if this is possible with boost-python.

In the meantime, this is how I handle RDKit with virtualenvs:

- Run `brew install rdkit` *outside* a virtualenv. This will install everything to `/usr/local/Cellar/rdkit`, and RDKit should work in your main python install outside a virtualenv.
- Copy the contents of `/usr/local/Cellar/rdkit/2014.09.2/lib/python2.7/site-packages` to `/Users/nathan/.virtualenvs/A0/lib/python2.7/site-packages`. RDKit should then work within that virtualenv.
- Every time you update RDKit or python, you will probably have to repeat this process. Not great, but it works.

You might also consider using Anaconda to create isolated Python environments instead of virtualenv:
https://github.com/rdkit/conda-rdkit

**Comment by supern8ent** [comment]
Thanks mcs07! I was able to brew install/compile outside the virtualenv, then copy rdkit directory from cellar to virtualenv, and now I have working rdkit.Chem in python.

**Comment by Richardxlin** [comment]
I get the below issue:

[ 61%] Linking CXX executable testweb3core
cd /tmp/cpp-ethereum20151031-52316-1f68o3a/libweb3core/test && /usr/local/Cellar/cmake/3.3.2/bin/cmake -E cmake_link_script CMakeFiles/testweb3core.dir/link.txt --verbose=1
/usr/local/Library/ENV/4.3/clang++   -std=c++11 -Wall -Wno-unknown-pragmas -Wextra -DSHAREDLIB -fPIC -fstack-protector-strong -Wstack-protector -O3 -DNDEBUG -DETH_RELEASE -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/testweb3core.dir/overlaydb.cpp.o CMakeFiles/testweb3core.dir/test.cpp.o CMakeFiles/testweb3core.dir/libdevcore/Base36.cpp.o CMakeFiles/testweb3core.dir/libdevcore/CommonJS.cpp.o CMakeFiles/testweb3core.dir/libdevcore/core.cpp.o CMakeFiles/testweb3core.dir/libdevcore/FixedHash.cpp.o CMakeFiles/testweb3core.dir/libdevcore/RangeMask.cpp.o CMakeFiles/testweb3core.dir/libdevcore/rlp.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/AES.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/crypto.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/hexPrefix.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/MemTrie.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/SecretStore.cpp.o CMakeFiles/testweb3core.dir/libdevcrypto/trie.cpp.o CMakeFiles/testweb3core.dir/libp2p/capability.cpp.o CMakeFiles/testweb3core.dir/libp2p/net.cpp.o CMakeFiles/testweb3core.dir/libp2p/peer.cpp.o CMakeFiles/testweb3core.dir/libp2p/rlpx.cpp.o  -o testweb3core  /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a -lpthread /usr/local/lib/libcryptopp.a ../../webthree-helpers/utils/secp256k1/libsecp256k1.a /usr/local/lib/libminiupnpc.dylib ../libp2p/libp2p.dylib /usr/local/lib/libboost_unit_test_framework-mt.a /usr/local/lib/libboost_regex-mt.a ../libdevcrypto/libdevcrypto.dylib ../libdevcore/libdevcore.dylib /usr/local/lib/libjsoncpp.dylib /usr/local/lib/libleveldb.dylib /usr/local/lib/libboost_thread-mt.a /usr/local/lib/libboost_random-mt.a /usr/local/lib/libboost_filesystem-mt.a /usr/local/lib/libboost_system-mt.a -lpthread ../../webthree-helpers/utils/libscrypt/libscrypt.dylib /usr/local/lib/libcryptopp.a ../../webthree-helpers/utils/secp256k1/libsecp256k1.a /usr/local/lib/libgmp.dylib /usr/local/lib/libminiupnpc.dylib 
[ 61%] Built target testweb3core
make: *** [all] Error 2
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
BuildError: Failed executing: make 
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action:
